# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

def shared_pods
     use_frameworks!

      pod 'R.swift', '~> 5.1'
      pod 'SnapKit', '~> 5.0.0'
      pod 'SQLite.swift', '~> 0.12.0'
    #  pod 'ADCountryPicker', '~> 2.1.0'
      pod 'PhoneNumberKit', '~> 3.0'
     # pod 'KeychainAccess'
     # pod 'SwiftOTP'
      pod 'SwiftyJSON'
    #  pod 'AWSMobileClient'
     # pod 'Firebase/Core'
     # pod 'Firebase/Messaging'
     # pod 'Firebase/RemoteConfig'
     # pod 'AWSS3'
      
      
      ## Object Mapper
      pod 'ObjectMapper', '~> 3.4'
      pod 'ObjectMapperAdditions/Core', '~> 6.0'
      
      ## Rx
      # Core RxSwift
      pod 'RxCocoa'

      
      # Moya
      pod 'Moya'
       pod 'Moya-ObjectMapper/RxSwift'
      
      # Alamofire
    #  pod 'Alamofire'
     # pod 'AlamofireImage'
     # pod 'RxAlamofire'
      
      # Community projects
      pod 'Action'
      pod 'NSObject+Rx'
      pod 'RxDataSources'
      pod 'RxGesture'
      pod 'RxKeyboard'
      pod 'RxOptional'
      pod 'RxSwiftExt'
      pod 'RxTest'

      # UI Components
       pod "SkeletonView"
      # pod 'MBProgressHUD'
      # pod 'UICircularProgressRing'
       pod 'VisualEffectView'
      # pod "AlignedCollectionViewFlowLayout"

       # pod 'SkyFloatingLabelTextField'
       # pod 'SmileLock'
       # pod 'Cloudinary', '~> 2.0'
      #  pod 'Stripe'
      #  pod 'Fabric'
      #  pod 'Crashlytics'
      #  pod 'FlagPhoneNumber'
      #  pod 'Localize-Swift', '~> 2.0'
    #    pod 'PhoneNumberKit'
        
      #    pod 'SwiftOTP'
      
end

target 'CarTrackCodeChallenge' do
    shared_pods
end

target 'CarTrackCodeChallengeTests' do
    shared_pods
end
